### PR TITLE
Fix TZ bug in Predictor

### PR DESCRIPTION
**Pull request by ieure**
Explanation in @cc93476

### CODE REVIEW

**Comment by vanvlack** [comment]
Why not submit a PR against cron4j proper?

**Comment by vanvlack** [comment]
I do see it's LGPL...ick. And it's not been released since 2011.......................

**Comment by ieure** [comment]
> Why not submit a PR against cron4j proper?

Because there isn't one, just a git mirror. The official repo is SVN, hosted on SourceForge. I emailed the author the same patch (this was what the official site recommended), but I'm assuming that getting a patched release isn't likely to happen, so I set up a mirror so we can maintain a patched fork.

**Comment by vanvlack** [comment]
+1

**Pull request closed without merging**
